import { useEffect, useMemo, useState, type PointerEvent as ReactPointerEvent } from 'react'
import { Activity, ArrowRight, ArrowUpRight, BarChart3, Brain, ChartCandlestick, Check, ChevronRight, CircleCheck, Copy, Github, Globe2, Link2, MessageCircle, Radio, ShieldCheck, Sparkles, Target, TrendingDown, TrendingUp, Users, Wallet, Zap } from 'lucide-react'

type Props = { onLaunchApp: () => void; onExploreTraders?: () => void }
type Candle = { open: number; close: number; high: number; low: number; volume: number }
type HoverPoint = { index: number; price: number; volume: number; x: number; y: number } | null

const CANDLES: Candle[] = [
  { open: .0823, close: .0836, high: .0845, low: .0816, volume: 7200 }, { open: .0836, close: .0828, high: .0842, low: .0819, volume: 5400 },
  { open: .0828, close: .0842, high: .0848, low: .0822, volume: 8300 }, { open: .0842, close: .0854, high: .0861, low: .0836, volume: 9100 },
  { open: .0854, close: .0848, high: .0862, low: .0841, volume: 6100 }, { open: .0848, close: .0863, high: .0872, low: .0842, volume: 10200 },
  { open: .0863, close: .0876, high: .0884, low: .0857, volume: 11800 }, { open: .0876, close: .0868, high: .0880, low: .0861, volume: 6700 },
  { open: .0868, close: .0889, high: .0898, low: .0862, volume: 12400 }, { open: .0889, close: .0905, high: .0914, low: .0881, volume: 13500 },
  { open: .0905, close: .0894, high: .0912, low: .0887, volume: 7600 }, { open: .0894, close: .0921, high: .0930, low: .0890, volume: 14800 },
  { open: .0921, close: .0937, high: .0945, low: .0914, volume: 16100 }, { open: .0937, close: .0929, high: .0947, low: .0919, volume: 8100 },
  { open: .0929, close: .0961, high: .0974, low: .0923, volume: 17300 }, { open: .0961, close: .0951, high: .0970, low: .0943, volume: 8900 },
  { open: .0951, close: .0974, high: .0986, low: .0947, volume: 15400 }, { open: .0974, close: .0992, high: .1002, low: .0968, volume: 17600 },
  { open: .0992, close: .0983, high: .1000, low: .0974, volume: 9200 }, { open: .0983, close: .1008, high: .1018, low: .0979, volume: 18700 },
  { open: .1008, close: .1022, high: .1032, low: .1000, volume: 20100 }, { open: .1022, close: .1014, high: .1037, low: .1006, volume: 10800 },
  { open: .1014, close: .1037, high: .1047, low: .1009, volume: 19300 }, { open: .1037, close: .1028, high: .1048, low: .1019, volume: 11500 },
]

const TICKER = ['MON BUY 0.4208','MON SELL 0.4179','ETH BUY 3,812','BTC BUY 118,240','MON BUY 0.4231','MON BUY 0.4256']
const CODE = ['0x7a9c31… · block 105200008','KURU / MON-USDC / BUY','CRE_ROUTE::SIGNAL_84','VERIFY::TRADER_ALICE','MONAD::FINALIZED','ORDERBOOK::SYNCED']

function Sparkline({ points, tone = 'emerald' }: { points: number[]; tone?: 'emerald'|'cyan'|'red' }) {
  const max = Math.max(...points), min = Math.min(...points), range = Math.max(max-min,.0001)
  const stroke = tone === 'red' ? '#fb7185' : tone === 'cyan' ? '#22d3ee' : '#34d399'
  const coords = points.map((p,i) => ({ x: i / Math.max(points.length-1,1) * 100, y: 28 - ((p-min)/range)*22 }))
  const path = coords.map((p,i) => (i?'L ':'M ') + p.x + ' ' + p.y).join(' ')
  return <svg viewBox="0 0 100 32" className="h-8 w-full"><path d={'M 0 30 ' + coords.map(p=>'L '+p.x+' '+p.y).join(' ') + ' L 100 32 L 0 32 Z'} fill={stroke} fillOpacity=".08"/><path d={path} fill="none" stroke={stroke} strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/></svg>
}

function Heading({ eyebrow, title, text }: { eyebrow:string; title:string; text:string }) {
  return <div className="max-w-3xl"><div className="mb-3 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.22em] text-emerald-400"><span className="h-px w-8 bg-emerald-400/70"/>{eyebrow}</div><h2 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl">{title}</h2><p className="mt-4 text-sm leading-7 text-zinc-500">{text}</p></div>
}

function TradingChart({ hover, onHover }: { hover:HoverPoint; onHover:(p:HoverPoint)=>void }) {
  const width=780, height=360, padX=30, padY=24
  const minPrice=Math.min(...CANDLES.map(c=>c.low))-.001
  const maxPrice=Math.max(...CANDLES.map(c=>c.high))+.001
  const chartWidth=width-padX*2, chartHeight=height-padY*2
  const xFor=(i:number)=>padX + (i/Math.max(CANDLES.length-1,1))*chartWidth
  const yFor=(p:number)=>padY + ((maxPrice-p)/(maxPrice-minPrice))*chartHeight
  const trend=CANDLES.map((c,i)=>(i?'L ':'M ')+xFor(i)+' '+yFor(c.close)).join(' ')
  const levels=[
    {label:'TP $0.1028', y:yFor(.1028), color:'#34d399', box:'#052318', width:115, x:width-147},
    {label:'ENTRY $0.0842', y:yFor(.0842), color:'#22d3ee', box:'#05202a', width:136, x:width-168},
    {label:'SL $0.0784', y:yFor(.0784), color:'#fb7185', box:'#2a0d15', width:108, x:width-140},
  ]
  const move=(e:ReactPointerEvent<SVGSVGElement>)=>{
    const rect=e.currentTarget.getBoundingClientRect(), localX=((e.clientX-rect.left)/rect.width)*width
    const index=Math.max(0,Math.min(CANDLES.length-1,Math.round(((localX-padX)/chartWidth)*(CANDLES.length-1))))
    const c=CANDLES[index]; if(!c)return
    onHover({index,price:c.close,volume:c.volume,x:xFor(index),y:yFor(c.close)})
  }
  return <div className="relative mt-4 overflow-hidden rounded-2xl border border-zinc-800/80 bg-[#050909]">
    <svg viewBox={'0 0 '+width+' '+height} className="h-[280px] w-full touch-none sm:h-[340px]" onPointerMove={move} onPointerLeave={()=>onHover(null)} role="img" aria-label="Interactive mock MON USDC chart">
      <defs><linearGradient id="afChartArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#34d399" stopOpacity=".2"/><stop offset="100%" stopColor="#34d399" stopOpacity="0"/></linearGradient><filter id="afChartGlow"><feGaussianBlur stdDeviation="2.8" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
      <rect width={width} height={height} fill="#050909"/>
      {Array.from({length:10}).map((_,i)=><line key={'v'+i} x1={padX+(i/9)*chartWidth} x2={padX+(i/9)*chartWidth} y1={padY} y2={height-padY} stroke="#64748b" strokeOpacity=".09" strokeDasharray="3 8"/>)}
      {Array.from({length:9}).map((_,i)=><line key={'h'+i} x1={padX} x2={width-padX} y1={padY+(i/8)*chartHeight} y2={padY+(i/8)*chartHeight} stroke="#64748b" strokeOpacity=".09" strokeDasharray="3 8"/>)}
      <path d={trend+' L '+xFor(CANDLES.length-1)+' '+(height-padY)+' L '+padX+' '+(height-padY)+' Z'} fill="url(#afChartArea)"/>
      <path d={trend} fill="none" stroke="#22d3ee" strokeWidth="1.4" strokeOpacity=".48"/>
      {CANDLES.map((c,i)=>{const x=xFor(i),oy=yFor(c.open),cy=yFor(c.close),hy=yFor(c.high),ly=yFor(c.low),bull=c.close>=c.open,color=bull?'#34d399':'#fb7185';return <g key={i}><line x1={x} x2={x} y1={hy} y2={ly} stroke={color} strokeWidth="2" strokeOpacity=".82"/><rect x={x-6} y={Math.min(oy,cy)} width="12" height={Math.max(Math.abs(cy-oy),3)} rx="2" fill={color} fillOpacity=".88" filter="url(#afChartGlow)"/></g>})}
      {levels.map(l=><g key={l.label}><line x1={padX} x2={width-padX} y1={l.y} y2={l.y} stroke={l.color} strokeOpacity=".82" strokeDasharray="5 8"/><rect x={l.x} y={l.y-13} width={l.width} height="26" rx="10" fill={l.box} stroke={l.color} strokeOpacity=".52"/><text x={l.x+l.width/2} y={l.y+5} textAnchor="middle" fill={l.color} fontSize="11" fontWeight="700">{l.label}</text></g>)}
      <circle cx={xFor(CANDLES.length-1)} cy={yFor(CANDLES[CANDLES.length-1].close)} r="8" fill="#34d399" fillOpacity=".09"/><circle cx={xFor(CANDLES.length-1)} cy={yFor(CANDLES[CANDLES.length-1].close)} r="3" fill="#34d399"/>
      {hover&&<g><line x1={hover.x} x2={hover.x} y1={padY} y2={height-padY} stroke="#cbd5e1" strokeOpacity=".2" strokeDasharray="4 7"/><line x1={padX} x2={width-padX} y1={hover.y} y2={hover.y} stroke="#cbd5e1" strokeOpacity=".15" strokeDasharray="4 7"/><circle cx={hover.x} cy={hover.y} r="7" fill="#22d3ee" fillOpacity=".12"/><circle cx={hover.x} cy={hover.y} r="3" fill="#22d3ee"/><g transform={'translate('+Math.min(hover.x+18,width-182)+' '+Math.max(hover.y-66,20)+')'}><rect width="164" height="58" rx="12" fill="#07110f" stroke="#334155" strokeOpacity=".8"/><text x="12" y="21" fill="#94a3b8" fontSize="10">Price</text><text x="12" y="41" fill="#f8fafc" fontSize="13" fontWeight="700">{'$'+hover.price.toFixed(4)}</text><text x="92" y="21" fill="#94a3b8" fontSize="10">Vol</text><text x="92" y="41" fill="#67e8f9" fontSize="13" fontWeight="700">{(hover.volume/1000).toFixed(1)+'k'}</text></g></g>}
      {[0,1,2,3,4].map(i=>{const p=maxPrice-((maxPrice-minPrice)/4)*i;return <text key={i} x={width-4} y={padY+(i/4)*chartHeight+4} textAnchor="end" fill="#52615f" fontSize="10">{'$'+p.toFixed(3)}</text>})}
    </svg>
    <div className="pointer-events-none absolute left-4 top-4 rounded-lg border border-zinc-800/70 bg-black/40 px-2.5 py-1 font-mono text-[9px] uppercase tracking-[0.16em] text-zinc-500 backdrop-blur">MON / USDC · 1H</div>
    <div className="absolute bottom-4 left-4 right-4 flex items-center justify-between text-[9px] uppercase tracking-[0.14em] text-zinc-600"><span>Prototype market visualization</span><span className="flex items-center gap-1.5 text-emerald-400"><span className="size-1.5 animate-pulse rounded-full bg-emerald-400"/>Streaming UI</span></div>
  </div>
}

export default function LandingPage({onLaunchApp,onExploreTraders}:Props){
  const [capital,setCapital]=useState(650)
  const [tickerIndex,setTickerIndex]=useState(0)
  const [pulse,setPulse]=useState(0)
  const [hover,setHover]=useState<HoverPoint>(null)
  useEffect(()=>{const a=window.setInterval(()=>setTickerIndex(v=>(v+1)%TICKER.length),1400);const b=window.setInterval(()=>setPulse(v=>v+1),950);return()=>{window.clearInterval(a);window.clearInterval(b)}},[])
  const mockRoi=36
  const profit=useMemo(()=>capital*mockRoi/100,[capital])
  const value=capital+profit
  const volume=12482900+pulse*1240
  const traders=1280+(pulse%7)
  const winRate=(64.2+(pulse%4)*.1).toFixed(1)
  const ticker=TICKER[tickerIndex]

  return <div className="relative min-h-screen overflow-x-hidden bg-zinc-950 text-white selection:bg-emerald-400/20">
    <style>{`
      @keyframes afFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-9px)}}
      @keyframes afSlow{0%,100%{transform:translate3d(0,0,0) rotate(0)}50%{transform:translate3d(10px,-15px,0) rotate(3deg)}}
      @keyframes afGlow{0%,100%{box-shadow:0 0 22px rgba(52,211,153,.08)}50%{box-shadow:0 0 46px rgba(52,211,153,.22)}}
      @keyframes afScan{0%{transform:translateY(-120%);opacity:0}12%{opacity:.7}80%{opacity:.35}100%{transform:translateY(500%);opacity:0}}
      @keyframes afCode{0%{transform:translateY(-25%);opacity:0}10%{opacity:.55}80%{opacity:.4}100%{transform:translateY(115%);opacity:0}}
      @keyframes afShimmer{0%{transform:translateX(-160%)}100%{transform:translateX(520%)}}
      @keyframes afGrid{0%,100%{opacity:.3}50%{opacity:.46}}
      .af-float{animation:afFloat 5s ease-in-out infinite}.af-slow{animation:afSlow 8s ease-in-out infinite}.af-glow{animation:afGlow 2.3s ease-in-out infinite}.af-scan{animation:afScan 7s linear infinite}.af-code{animation:afCode 12s linear infinite}.af-grid{animation:afGrid 7s ease-in-out infinite}.af-shimmer{animation:afShimmer 2.4s linear infinite}
      @media (prefers-reduced-motion:reduce){.af-float,.af-slow,.af-glow,.af-scan,.af-code,.af-grid,.af-shimmer{animation:none!important}}
    `}</style>

    <div className="pointer-events-none fixed inset-0 -z-20 overflow-hidden">
      <div className="absolute inset-0 bg-zinc-950"/>
      <div className="af-grid absolute inset-0 bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:44px_44px]"/>
      <div className="absolute left-[-14rem] top-[-12rem] h-[42rem] w-[42rem] rounded-full bg-emerald-500/10 blur-[145px]"/>
      <div className="absolute right-[-12rem] top-[8rem] h-[36rem] w-[36rem] rounded-full bg-cyan-500/[.08] blur-[145px]"/>
      <div className="absolute bottom-[-15rem] left-1/2 h-[38rem] w-[44rem] -translate-x-1/2 rounded-full bg-purple-500/[.08] blur-[155px]"/>
      <div className="absolute left-[9%] top-[18%] size-2 rounded-full bg-emerald-300 shadow-[0_0_20px_rgba(52,211,153,.9)]"/>
      <div className="absolute right-[17%] top-[32%] size-1.5 rounded-full bg-cyan-300 shadow-[0_0_16px_rgba(34,211,238,.9)]"/>
      <div className="absolute left-[42%] bottom-[26%] size-1 rounded-full bg-purple-300 shadow-[0_0_14px_rgba(168,85,247,.9)]"/>
      <div className="absolute right-[8%] bottom-[15%] size-2 rounded-full bg-emerald-300/80 shadow-[0_0_17px_rgba(52,211,153,.8)]"/>
      <div className="absolute left-[10%] top-[9%] size-16 rotate-45 border border-emerald-400/10"/>
      <div className="af-slow absolute right-[7%] top-[20%] size-24 rotate-12 rounded-3xl border border-cyan-400/10"/>
      <div className="absolute bottom-[18%] left-[6%] size-20 rounded-full border border-purple-400/10"/>
      {CODE.map((code,index)=><div key={code} className="af-code absolute hidden font-mono text-[9px] tracking-[.14em] text-emerald-300/[.13] sm:block" style={{left:(8+index*14)+'%',top:(-10-index*4)+'%',animationDelay:(index*1.7)+'s'}}><div>{code}</div><div className="ml-4 mt-8">0x{(index+4).toString(16)}f9a1</div><div className="mt-8">SYNC::{index+1}</div><div className="mt-8">████ {index*7+3}%</div></div>)}
      <div className="af-scan absolute left-0 right-0 h-32 bg-gradient-to-b from-transparent via-emerald-400/[.035] to-transparent"/>
    </div>

    <div className="pointer-events-none fixed inset-0 -z-10 hidden md:block">
      <div className="absolute left-4 top-24 h-px w-44 bg-gradient-to-r from-emerald-400/40 to-transparent"/><div className="absolute right-4 top-24 h-px w-44 bg-gradient-to-l from-cyan-400/40 to-transparent"/><div className="absolute bottom-5 left-4 h-px w-56 bg-gradient-to-r from-purple-400/25 to-transparent"/><div className="absolute bottom-5 right-4 h-px w-56 bg-gradient-to-l from-emerald-400/25 to-transparent"/><div className="absolute left-4 top-24 h-24 w-px bg-gradient-to-b from-emerald-400/35 to-transparent"/><div className="absolute right-4 top-24 h-24 w-px bg-gradient-to-b from-cyan-400/35 to-transparent"/>
    </div>

    <header className="sticky top-0 z-50 border-b border-zinc-800/70 bg-zinc-950/75 backdrop-blur-2xl">
      <div className="mx-auto flex h-16 max-w-[1500px] items-center justify-between px-4 sm:px-6 lg:px-8">
        <button onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} className="group flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl border border-emerald-400/30 bg-emerald-400/10 text-emerald-300 shadow-[0_0_24px_rgba(52,211,153,.12)]"><ChartCandlestick size={18}/></span><span className="font-semibold tracking-tight">Alpha<span className="text-emerald-400">Feed</span></span><span className="hidden rounded-full border border-zinc-800 bg-zinc-900/70 px-2 py-0.5 font-mono text-[8px] tracking-[.14em] text-zinc-500 sm:block">TERMINAL</span></button>
        <nav className="hidden items-center gap-7 lg:flex">{[['Features','features'],['Terminal','terminal'],['Leaderboard','leaderboard'],['Infrastructure','infrastructure']].map(([label,id])=><button key={id} onClick={()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'})} className="text-xs text-zinc-500 transition hover:text-white">{label}</button>)}</nav>
        <button onClick={onLaunchApp} className="group relative flex items-center gap-2 overflow-hidden rounded-xl border border-emerald-300/40 bg-gradient-to-r from-emerald-500 to-teal-400 px-4 py-2.5 text-xs font-bold text-zinc-950 shadow-[0_0_35px_rgba(52,211,153,.18)] transition hover:-translate-y-0.5 hover:shadow-[0_0_50px_rgba(52,211,153,.3)]"><span className="absolute inset-y-0 -left-10 w-10 skew-x-[-18deg] bg-white/30 blur-md af-shimmer"/><Zap size={14}/>Launch Terminal<ArrowRight size={14} className="transition-transform group-hover:translate-x-1"/></button>
      </div>
    </header>

    <main>
      <section className="mx-auto max-w-[1500px] px-4 pb-16 pt-14 sm:px-6 sm:pb-20 sm:pt-20 lg:px-8 lg:pt-24">
        <div className="grid items-start gap-12 lg:grid-cols-[.94fr_1.06fr] lg:gap-16">
          <div className="relative">
            <div className="absolute -left-10 top-12 h-56 w-56 rounded-full bg-emerald-400/10 blur-[95px]"/>
            <div className="relative">
              <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-emerald-400/15 bg-emerald-400/[.05] px-3 py-1.5 font-mono text-[9px] uppercase tracking-[.2em] text-emerald-300"><span className="size-1.5 animate-pulse rounded-full bg-emerald-400 shadow-[0_0_10px_rgba(52,211,153,.9)]"/>Social trading infrastructure</div>
              <h1 className="max-w-4xl text-5xl font-semibold leading-[.92] tracking-[-.055em] text-white sm:text-6xl lg:text-[5.2rem]">Social Trading<span className="block">Meets</span><span className="mt-1 block bg-gradient-to-r from-emerald-400 via-cyan-400 to-indigo-500 bg-clip-text text-transparent drop-shadow-[0_0_15px_rgba(52,211,153,.3)]">On-Chain Execution.</span></h1>
              <p className="mt-7 max-w-2xl text-sm leading-7 text-zinc-400 sm:text-base">Discover high-signal traders, inspect chart context and explore programmable copy-trading workflows built around Monad, Kuru orderbooks, Chainlink CRE and AI-assisted analysis.</p>
              <div className="mt-6 flex flex-wrap gap-2"><span className="rounded-full border border-emerald-400/25 bg-emerald-400/[.08] px-3 py-1.5 text-[10px] font-medium text-emerald-300 backdrop-blur-xl">Monad</span><span className="rounded-full border border-cyan-400/20 bg-cyan-400/[.06] px-3 py-1.5 text-[10px] font-medium text-cyan-300 backdrop-blur-xl">Kuru orderbooks</span><span className="rounded-full border border-indigo-400/20 bg-indigo-400/[.06] px-3 py-1.5 text-[10px] font-medium text-indigo-300 backdrop-blur-xl">Chainlink CRE</span></div>
              <div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={onLaunchApp} className="group relative flex items-center justify-center gap-2 overflow-hidden rounded-2xl bg-gradient-to-r from-emerald-500 to-teal-400 px-6 py-4 text-sm font-bold text-zinc-950 shadow-[0_0_42px_rgba(52,211,153,.22)] transition hover:-translate-y-1 hover:shadow-[0_0_65px_rgba(52,211,153,.34)]"><span className="absolute inset-y-0 -left-20 w-16 skew-x-[-18deg] bg-white/30 blur-lg transition-transform duration-700 group-hover:translate-x-[500px]"/>Launch App<ArrowRight size={16} className="transition-transform group-hover:translate-x-1"/></button><button onClick={onExploreTraders??(()=>document.getElementById('leaderboard')?.scrollIntoView({behavior:'smooth'}))} className="group relative flex items-center justify-center gap-2 overflow-hidden rounded-2xl border border-zinc-700 bg-white/[.035] px-6 py-4 text-sm font-semibold text-zinc-200 shadow-[0_15px_45px_rgba(0,0,0,.18)] backdrop-blur-xl transition hover:-translate-y-1 hover:border-emerald-400/30 hover:bg-white/[.06]"><span className="absolute inset-y-0 -left-full w-1/2 bg-gradient-to-r from-transparent via-white/[.07] to-transparent transition-transform duration-700 group-hover:translate-x-[320%]"/><Users size={16}/>Explore Traders<ArrowUpRight size={15} className="transition-transform group-hover:translate-x-0.5"/></button></div>

              <div className="mt-10 overflow-hidden rounded-2xl border border-zinc-800/80 bg-zinc-900/45 shadow-[0_20px_60px_rgba(0,0,0,.18)] backdrop-blur-xl">
                <div className="flex items-center justify-between border-b border-zinc-800/70 px-4 py-3"><div className="flex items-center gap-2 text-[9px] uppercase tracking-[.18em] text-zinc-500"><Radio size={13} className="text-emerald-400"/>Live Stats</div><div className="flex items-center gap-2 font-mono text-[9px] text-emerald-400"><span className="size-1.5 animate-pulse rounded-full bg-emerald-400 shadow-[0_0_12px_rgba(52,211,153,.9)]"/>STREAMING</div></div>
                <div className="grid grid-cols-2 divide-x divide-y divide-zinc-800/70 sm:grid-cols-4 sm:divide-y-0">
                  {[['Volume Copied','$'+volume.toLocaleString()+'+',Wallet,'emerald'],['Active Traders',traders.toLocaleString()+'+',Users,'cyan'],['Average Win Rate',winRate+'%',TrendingUp,'emerald'],['Execution Layer','Monad / Kuru',Zap,'cyan']].map(([label,display,Icon,tone])=><div key={String(label)} className="relative p-4"><div className="flex items-center gap-2 text-[9px] uppercase tracking-[.14em] text-zinc-600"><Icon size={12} className={tone==='cyan'?'text-cyan-400':'text-emerald-400'}/>{label}</div><div className="mt-2 text-sm font-semibold text-zinc-100 sm:text-base">{display}</div><Sparkline points={[6,6.9,6.4,7.8,7.2,8.8,8.2+(pulse%2)*.8]} tone={tone==='cyan'?'cyan':'emerald'}/></div>)}
                </div>
                <div className="border-t border-zinc-800/70 bg-black/20 px-4 py-2.5"><div className="flex items-center gap-2 overflow-hidden font-mono text-[9px] text-zinc-500"><span className="shrink-0 text-emerald-400">LIVE FEED</span><span className="text-zinc-700">/</span><span className="truncate">{ticker}</span><span className="ml-auto hidden shrink-0 text-cyan-300 sm:block">+{(pulse%5)+1}.2%</span></div></div>
              </div>

              <div className="mt-5 overflow-hidden rounded-2xl border border-emerald-400/10 bg-gradient-to-br from-emerald-400/[.045] via-zinc-900/70 to-cyan-400/[.035] p-5 shadow-[0_25px_80px_rgba(52,211,153,.06)] backdrop-blur-xl">
                <div className="flex items-start justify-between gap-5"><div><div className="flex items-center gap-2 text-[10px] uppercase tracking-[.18em] text-emerald-400"><Sparkles size={13}/>Estimated Copy Returns</div><h3 className="mt-2 text-lg font-semibold">Configure your copy capital.</h3><p className="mt-1 text-xs leading-5 text-zinc-600">Gamified simulator with a fixed mock ROI.</p></div><div className="rounded-xl border border-zinc-800 bg-zinc-950/75 px-3 py-2 text-right"><div className="text-[8px] uppercase tracking-[.16em] text-zinc-600">Mock ROI</div><div className="mt-1 text-lg font-bold text-emerald-400">+${mockRoi}%</div></div></div>
                <div className="mt-6 flex items-end justify-between"><div><div className="text-[9px] uppercase tracking-[.14em] text-zinc-600">Copy Capital</div><div className="mt-1 text-3xl font-semibold tracking-tight">$${capital.toLocaleString()}</div></div><div className="text-right"><div className="text-[9px] uppercase tracking-[.14em] text-zinc-600">Hypothetical Profit</div><div className="mt-1 text-lg font-bold text-emerald-400">+$${profit.toFixed(0)}</div></div></div>
                <div className="relative mt-6"><div className="pointer-events-none absolute inset-x-0 top-1/2 h-5 -translate-y-1/2 rounded-full bg-emerald-400/[.05] blur-lg"/><input aria-label="Copy capital" type="range" min="100" max="5000" step="25" value={capital} onChange={e=>setCapital(Number(e.target.value))} className="relative z-10 h-1.5 w-full cursor-pointer appearance-none rounded-full bg-zinc-800 accent-emerald-400"/><div className="mt-2 flex justify-between text-[9px] font-mono text-zinc-600"><span>$100</span><span>$5,000</span></div></div>
                <div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl border border-zinc-800 bg-black/20 p-3"><div className="text-[8px] uppercase tracking-[.14em] text-zinc-600">Hypothetical Value</div><div className="mt-1 text-base font-semibold">$${value.toFixed(0)}</div><Sparkline points={[2,2.2,2.6,3.1,3.6,4.2,5]} tone="cyan"/></div><div className="rounded-xl border border-emerald-500/10 bg-emerald-400/[.025] p-3"><div className="text-[8px] uppercase tracking-[.14em] text-zinc-600">Model Signal</div><div className="mt-1 flex items-center gap-1.5 text-base font-semibold text-emerald-400"><span className="size-1.5 animate-pulse rounded-full bg-emerald-400"/>Positive</div><Sparkline points={[3,3.8,3.2,4.4,4.7,5.8,6.8]}/></div></div>
                <div className="mt-4 rounded-xl border border-amber-500/10 bg-amber-500/[.03] px-3 py-2.5 text-[9px] leading-4 text-zinc-600">Prototype only. Fixed mock return; this does not predict future performance or submit a real trade.</div>
              </div>
            </div>

            <div id="terminal" className="relative scroll-mt-24">
              <div className="absolute -inset-10 rounded-[3rem] bg-gradient-to-br from-emerald-500/10 via-purple-500/5 to-cyan-500/10 blur-[72px]"/>
              <div className="af-float relative overflow-hidden rounded-[2rem] border border-zinc-800/80 bg-zinc-900/60 shadow-[0_0_50px_rgba(16,185,129,.15)] backdrop-blur-xl">
                <div className="absolute inset-x-0 top-0 h-24 bg-gradient-to-b from-white/[.04] to-transparent"/>
                <div className="relative flex items-center justify-between border-b border-zinc-800/80 px-4 py-3"><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-rose-400/70"/><span className="size-2 rounded-full bg-amber-300/70"/><span className="size-2 rounded-full bg-emerald-400/80"/></div><div className="font-mono text-[9px] uppercase tracking-[.16em] text-zinc-500">AlphaFeed / Live Terminal</div><div className="flex items-center gap-2 text-[9px] text-emerald-400"><span className="size-1.5 animate-pulse rounded-full bg-emerald-400 shadow-[0_0_10px_rgba(52,211,153,.8)]"/>Live on Monad Mainnet</div></div>
                <div className="flex items-center gap-3 overflow-hidden border-b border-zinc-800/70 bg-black/20 px-4 py-2.5 font-mono text-[9px]"><span className="shrink-0 text-emerald-400">MARKET STREAM</span><span className="text-zinc-700">/</span><span className="truncate text-zinc-400">{ticker}</span><div className="ml-auto hidden items-center gap-3 sm:flex"><span className="text-zinc-600">SPREAD</span><span className="text-zinc-300">0.14%</span><span className="text-zinc-600">VOL</span><span className="text-cyan-300">$1.28M</span></div></div>

                <div className="relative p-4 sm:p-5">
                  <div className="flex items-center justify-between gap-4 rounded-2xl border border-zinc-800/80 bg-black/20 p-4"><div className="flex min-w-0 items-center gap-3"><div className="grid size-11 shrink-0 place-items-center rounded-full border border-emerald-400/25 bg-gradient-to-br from-emerald-300/30 to-cyan-400/10 text-xs font-bold text-emerald-200 shadow-[0_0_24px_rgba(52,211,153,.12)]">AC</div><div className="min-w-0"><div className="flex items-center gap-1.5 text-sm font-semibold">Alice Chen<ShieldCheck size={14} className="text-emerald-400 drop-shadow-[0_0_7px_rgba(52,211,153,.6)]"/></div><div className="mt-0.5 truncate text-[10px] text-zinc-600">@alice_alpha · Momentum & breakouts</div></div></div><div className="rounded-xl border border-emerald-400/15 bg-emerald-400/[.05] px-3 py-2 text-right"><div className="text-[8px] uppercase tracking-[.15em] text-zinc-600">ROI</div><div className="mt-0.5 text-lg font-bold text-emerald-400">+34.7%</div></div></div>
                  <div className="mt-4 flex items-end justify-between gap-4"><div><div className="flex items-center gap-2 text-[9px] uppercase tracking-[.16em] text-zinc-600"><span className="size-1.5 animate-pulse rounded-full bg-emerald-400"/>Live asset</div><div className="mt-1 flex items-center gap-2 text-2xl font-semibold tracking-tight">MON<span className="rounded-md border border-emerald-400/20 bg-emerald-400/[.07] px-2 py-0.5 font-mono text-[9px] text-emerald-400">BUY</span></div></div><div className="text-right"><div className="text-[9px] uppercase tracking-[.15em] text-zinc-600">Mark</div><div className="mt-1 text-xl font-semibold text-zinc-100">$0.4208</div></div></div>
                  <TradingChart hover={hover} onHover={setHover}/>
                  <div className="mt-3 flex flex-wrap items-center justify-between gap-3 px-1"><div className="flex items-center gap-4 text-[9px] uppercase tracking-[.12em] text-zinc-600"><span className="flex items-center gap-1.5"><span className="h-1.5 w-4 rounded-full bg-emerald-400"/>Bull</span><span className="flex items-center gap-1.5"><span className="h-1.5 w-4 rounded-full bg-rose-400"/>Bear</span><span className="flex items-center gap-1.5"><span className="h-1.5 w-4 rounded-full bg-cyan-400"/>Trend</span></div><span className="font-mono text-[9px] text-zinc-600">Hover chart for price + volume</span></div>
                  <div className="mt-4 grid grid-cols-3 gap-2.5"><div className="rounded-xl border border-cyan-400/10 bg-cyan-400/[.025] p-3"><div className="flex items-center justify-between text-[8px] uppercase tracking-[.14em] text-zinc-600"><span>Entry</span><Target size={12} className="text-cyan-400"/></div><div className="mt-2 font-mono text-xs font-semibold text-cyan-300">$0.0842</div><Sparkline points={[2,2.1,1.9,2.2,2.05,2.3,2.4]} tone="cyan"/></div><div className="rounded-xl border border-emerald-400/10 bg-emerald-400/[.025] p-3"><div className="flex items-center justify-between text-[8px] uppercase tracking-[.14em] text-zinc-600"><span>Target</span><TrendingUp size={12} className="text-emerald-400"/></div><div className="mt-2 font-mono text-xs font-semibold text-emerald-300">$0.1028</div><Sparkline points={[2,2.3,2.5,3.1,3.4,4,4.5]}/></div><div className="rounded-xl border border-rose-400/10 bg-rose-400/[.025] p-3"><div className="flex items-center justify-between text-[8px] uppercase tracking-[.14em] text-zinc-600"><span>Stop</span><TrendingDown size={12} className="text-rose-400"/></div><div className="mt-2 font-mono text-xs font-semibold text-rose-300">$0.0784</div><Sparkline points={[4.7,4.3,4.4,3.9,3.5,3.4,3.1]} tone="red"/></div></div>
                  <div className="mt-4 grid gap-2 sm:grid-cols-3"><div className="flex items-center gap-2 rounded-xl border border-zinc-800 bg-black/20 px-3 py-2.5"><Globe2 size={13} className="text-emerald-400"/><div><div className="text-[8px] uppercase tracking-[.13em] text-zinc-600">Network</div><div className="text-[10px] text-zinc-300">Monad</div></div></div><div className="flex items-center gap-2 rounded-xl border border-zinc-800 bg-black/20 px-3 py-2.5"><BarChart3 size={13} className="text-cyan-400"/><div><div className="text-[8px] uppercase tracking-[.13em] text-zinc-600">Orderbook</div><div className="text-[10px] text-zinc-300">Kuru</div></div></div><div className="flex items-center gap-2 rounded-xl border border-zinc-800 bg-black/20 px-3 py-2.5"><ShieldCheck size={13} className="text-emerald-400"/><div><div className="text-[8px] uppercase tracking-[.13em] text-zinc-600">Status</div><div className="text-[10px] text-emerald-300">Verified</div></div></div></div>
                  <button onClick={onLaunchApp} className="af-glow group relative mt-4 flex w-full items-center justify-center gap-2 overflow-hidden rounded-2xl bg-gradient-to-r from-emerald-500 via-emerald-400 to-teal-400 py-3.5 text-sm font-bold text-zinc-950 transition hover:-translate-y-0.5"><span className="absolute inset-y-0 -left-16 w-12 skew-x-[-18deg] bg-white/30 blur-lg transition-transform duration-700 group-hover:translate-x-[700px]"/><Copy size={15}/>Copy Trade Preview<ArrowRight size={15} className="transition-transform group-hover:translate-x-1"/></button>
                  <div className="mt-3 flex items-center justify-center gap-2 text-[8px] uppercase tracking-[.15em] text-zinc-700"><ShieldCheck size={11} className="text-zinc-600"/>Prototype interface · no real order submitted</div>
                </div>
              </div>
              <div className="af-slow absolute -right-6 top-[17%] hidden w-40 rounded-2xl border border-cyan-400/10 bg-zinc-900/70 p-3 shadow-[0_0_30px_rgba(34,211,238,.07)] backdrop-blur-xl xl:block"><div className="flex items-center justify-between"><span className="text-[8px] uppercase tracking-[.14em] text-zinc-600">Feed Pulse</span><Activity size={12} className="text-cyan-400"/></div><div className="mt-2 text-sm font-semibold">328 ideas</div><Sparkline points={[3,3.6,3.4,4.2,4.8,5.2,6.1]} tone="cyan"/></div>
              <div className="af-float absolute -left-7 bottom-[7%] hidden w-44 rounded-2xl border border-emerald-400/10 bg-zinc-900/75 p-3 shadow-[0_0_30px_rgba(52,211,153,.07)] backdrop-blur-xl xl:block"><div className="flex items-center gap-2 text-[8px] uppercase tracking-[.14em] text-zinc-600"><Link2 size={12} className="text-emerald-400"/>Execution route</div><div className="mt-2 font-mono text-[10px] text-zinc-300">MON → KURU → CRE</div><div className="mt-2 flex items-center gap-2 text-[9px] text-emerald-400"><span className="size-1.5 animate-pulse rounded-full bg-emerald-400"/>Verified route</div></div>
            </div>
          </div>
        </section>

        <section className="border-y border-zinc-800/70 bg-zinc-900/20"><div className="mx-auto grid max-w-[1500px] grid-cols-2 divide-x divide-y divide-zinc-800/70 sm:grid-cols-4 sm:divide-y-0">{[[Search,'01','Discover','Trader intelligence'],[Brain,'02','Analyze','Chart-first context'],[ShieldCheck,'03','Verify','On-chain reputation'],[Zap,'04','Automate','Programmable workflows']].map(([Icon,number,title,description])=><div key={String(number)} className="group relative overflow-hidden px-5 py-7 sm:px-8"><div className="absolute right-5 top-3 text-5xl font-black text-white/[.025]">{number}</div><Icon size={18} className="text-emerald-400 transition-transform group-hover:scale-110"/><div className="mt-5 text-[10px] uppercase tracking-[.14em] text-zinc-600">{title}</div><div className="mt-1 text-sm font-medium text-zinc-300">{description}</div></div>)}</div></section>

        <section id="features" className="scroll-mt-20 px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1500px]"><Heading eyebrow="The AlphaFeed Loop" title="A social feed that feels like a cyber trading desk." text="Discover, analyze, verify and automate through one dense, chart-first product surface."/><div className="mt-12 grid gap-4 md:grid-cols-3">{[[Search,'01','Discover','Find traders, signals and reputation without leaving the terminal.',['Profiles','Signals','Leaderboard']],[Brain,'02','Analyze','Move from a social post into chart context, risk levels and AI-assisted interpretation.',['Charts','R:R','AI Context']],[Zap,'03','Automate','Prototype copy rules and programmable execution flows without changing interfaces.',['Copy Rules','CRE','Kuru']]].map(([Icon,number,title,description,chips])=><div key={String(number)} className="group relative overflow-hidden rounded-3xl border border-zinc-800 bg-zinc-900/45 p-6 shadow-[0_25px_80px_rgba(0,0,0,.18)] backdrop-blur-xl transition duration-300 hover:-translate-y-1 hover:border-emerald-400/20"><div className="absolute -right-8 -top-8 size-32 rounded-full bg-emerald-400/[.05] blur-3xl transition group-hover:bg-emerald-400/[.1]"/><div className="relative flex items-start justify-between"><div className="grid size-11 place-items-center rounded-xl border border-emerald-400/15 bg-emerald-400/[.06] text-emerald-300"><Icon size={20}/></div><span className="text-5xl font-black tracking-tight text-white/[.03]">{number}</span></div><h3 className="relative mt-8 text-xl font-semibold">{title}</h3><p className="relative mt-3 text-sm leading-6 text-zinc-500">{description}</p><div className="relative mt-6 flex flex-wrap gap-2">{(chips as string[]).map(chip=><span key={chip} className="rounded-full border border-zinc-800 bg-zinc-950/70 px-2.5 py-1 text-[9px] uppercase tracking-[.12em] text-zinc-600">{chip}</span>)}</div><div className="relative mt-7 flex items-center gap-2 text-[10px] uppercase tracking-[.15em] text-emerald-400">Explore module<ChevronRight size={14} className="transition-transform group-hover:translate-x-1"/></div></div>)}</div></div></section>

        <section id="leaderboard" className="scroll-mt-20 border-y border-zinc-800/70 bg-zinc-900/[.14] px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-[1500px] items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><Heading eyebrow="Leaderboard Intelligence" title="Data-rich trader discovery." text="Performance becomes a compact decision layer with reputation, micro charts and verification states."/><div className="grid gap-3">{[['Alice Chen','@alice_alpha','+34.7%','68.2%','12.4K'],['David Rao','@davidflow','+28.3%','71.4%','8.2K'],['Sarah Malik','@sarahcharts','+24.1%','65.0%','6.4K']].map(([name,handle,roi,win,followers],i)=><div key={handle} className="group relative overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900/50 p-4 transition hover:border-emerald-400/20 hover:bg-zinc-900/70"><div className="absolute inset-y-0 left-0 w-1 bg-gradient-to-b from-emerald-400/0 via-emerald-400/40 to-emerald-400/0 opacity-0 transition group-hover:opacity-100"/><div className="flex flex-wrap items-center gap-4"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full border border-zinc-700 bg-gradient-to-br from-emerald-300/20 to-cyan-400/10 text-[10px] font-bold text-zinc-200">{name.split(' ').map(part=>part[0]).join('')}</div><div><div className="flex items-center gap-1.5 text-sm font-semibold">{name}<ShieldCheck size={13} className="text-emerald-400"/></div><div className="text-[10px] text-zinc-600">{handle}</div></div></div><div className="ml-auto grid grid-cols-3 gap-5 text-right"><div><div className="text-[8px] uppercase tracking-[.12em] text-zinc-600">ROI</div><div className="mt-1 text-sm font-semibold text-emerald-400">{roi}</div></div><div><div className="text-[8px] uppercase tracking-[.12em] text-zinc-600">Win</div><div className="mt-1 text-sm font-semibold text-zinc-200">{win}</div></div><div><div className="text-[8px] uppercase tracking-[.12em] text-zinc-600">Followers</div><div className="mt-1 text-sm font-semibold text-zinc-200">{followers}</div></div></div></div><div className="mt-3"><Sparkline points={i===0?[2,2.4,2.3,3,3.4,4.2,5]:i===1?[2.5,2.4,3,2.8,3.6,4.1,4.7]:[2,2.3,2.2,2.8,3.1,3.7,4.2]} tone={i===1?'cyan':'emerald'}/></div></div>)}</div></div></section>

        <section id="infrastructure" className="scroll-mt-20 px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1500px]"><Heading eyebrow="Infrastructure" title="Web3 rails rendered as terminal telemetry." text="Monad, Kuru, Chainlink CRE and Hunyuan AI become visible infrastructure modules rather than generic marketing badges."/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Monad','High-performance EVM execution','M','emerald'],['Kuru DEX','On-chain orderbook infrastructure','K','cyan'],['Chainlink CRE','Composable execution layer','C','indigo'],['Hunyuan AI','AI-assisted trade analysis','AI','purple']].map(([name,description,mark,tone])=>{const cls=tone==='cyan'?'border-cyan-400/20 bg-cyan-400/[.05] text-cyan-300':tone==='indigo'?'border-indigo-400/20 bg-indigo-400/[.05] text-indigo-300':tone==='purple'?'border-purple-400/20 bg-purple-400/[.05] text-purple-300':'border-emerald-400/20 bg-emerald-400/[.05] text-emerald-300';return <div key={name} className="group rounded-3xl border border-zinc-800 bg-zinc-900/45 p-6 backdrop-blur-xl transition hover:-translate-y-1 hover:border-emerald-400/20"><div className="flex items-center justify-between"><div className={'grid size-11 place-items-center rounded-xl border text-xs font-black '+cls}>{mark}</div><Link2 size={15} className="text-zinc-700 transition group-hover:text-emerald-400"/></div><h3 className="mt-7 font-semibold">{name}</h3><p className="mt-2 text-xs leading-5 text-zinc-600">{description}</p><div className="mt-6 flex items-center justify-between"><span className="rounded-full border border-zinc-800 bg-zinc-950 px-2.5 py-1 text-[8px] uppercase tracking-[.12em] text-zinc-600">Integrated UI</span><Check size={14} className="text-emerald-400"/></div></div>})}</div><div className="mt-10 rounded-3xl border border-zinc-800 bg-zinc-900/45 p-5 backdrop-blur-xl sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-[9px] uppercase tracking-[.18em] text-emerald-400"><CircleCheck size={13}/>Prototype architecture</div><h3 className="mt-2 text-xl font-semibold">A continuous signal → analysis → execution loop.</h3></div><div className="flex flex-wrap gap-2 text-[9px] font-mono uppercase tracking-[.12em] text-zinc-500">{['DISCOVER','→','ANALYZE','→','VERIFY','→','AUTOMATE'].map((item,i)=><span key={item+i} className={item==='→'?'text-zinc-700':'rounded-full border border-zinc-800 bg-zinc-950 px-2.5 py-1.5'}>{item}</span>)}</div></div></div></div></section>
      </main>

      <footer className="border-t border-zinc-800/80 bg-zinc-950"><div className="mx-auto flex max-w-[1500px] flex-col justify-between gap-8 px-4 py-12 sm:px-6 md:flex-row lg:px-8"><div><div className="flex items-center gap-2 font-semibold"><span className="grid size-8 place-items-center rounded-lg bg-emerald-400 text-zinc-950">α</span>Alpha<span className="text-emerald-400">Feed</span></div><p className="mt-3 max-w-md text-xs leading-6 text-zinc-600">Cinematic social-trading interface for trader discovery, chart intelligence and programmable on-chain workflows.</p><div className="mt-4 flex items-center gap-2 text-[8px] uppercase tracking-[.15em] text-zinc-700"><ShieldCheck size={11}/>Prototype UI · simulated data</div></div><div className="flex items-start gap-2"><a href="https://x.com" target="_blank" rel="noreferrer" aria-label="X" className="grid size-10 place-items-center rounded-xl border border-zinc-800 text-zinc-500 transition hover:border-zinc-700 hover:text-white">𝕏</a><a href="https://github.com" target="_blank" rel="noreferrer" aria-label="GitHub" className="grid size-10 place-items-center rounded-xl border border-zinc-800 text-zinc-500 transition hover:border-zinc-700 hover:text-white"><Github size={15}/></a><a href="https://discord.com" target="_blank" rel="noreferrer" aria-label="Discord" className="grid size-10 place-items-center rounded-xl border border-zinc-800 text-zinc-500 transition hover:border-zinc-700 hover:text-white"><MessageCircle size={15}/></a></div></div></footer>
    </div>
  )
}
